### ISSUE TITLE
Error when Applying Camera Shakify to a New Camera in a File with Linked Libraries

### ISSUE THREAD

**Issue by 0xCarnival** [EatTheFuture/camera_shakify#34]
### Description
When attempting to use the Camera Shakify addon on a newly created camera in a Blender scene, a runtime error occurs if the Blender file contains linked libraries or scenes. The error seems related to the presence of linked collections, even though the new camera and its associated objects are not part of those linked collections.

### Error Log
Traceback (most recent call last):
  File "/path/to/Library/Application Support/Blender/4.3/extensions/blender_org/camera_shakify/__init__.py", line 453, in execute
    rebuild_camera_shakes(camera, context)
  File "/path/to/Library/Application Support/Blender/4.3/extensions/blender_org/camera_shakify/__init__.py", line 363, in rebuild_camera_shakes
    build_single_shake(camera, shake_item_index, collection, context)
  File "/path/to/Library/Application Support/Blender/4.3/extensions/blender_org/camera_shakify/__init__.py", line 174, in build_single_shake
    collection.objects.link(shake_object)
RuntimeError: Error: Could not (un)link the object 'CameraShakify.v2_Camera_0' because the collection 'CameraShakify.v2' is linked

### Steps to Reproduce
Open a Blender file containing linked libraries or scenes.
Create a new camera in a local scene or collection.
Apply Camera Shakify to the newly created camera.
Observe the error when the addon attempts to rebuild camera shakes.
### Expected Behavior
Camera Shakify should function normally for newly created cameras in a local scene, regardless of the presence of linked libraries elsewhere in the Blender file.

### Actual Behavior
The addon raises a runtime error when attempting to link objects to a collection that happens to be linked, even though the new camera and its objects are not part of that collection.

### Environment
Blender Version: 4.3
Camera Shakify Version: Latest
Operating System: macOS

### Additional Notes
This issue seems to arise because the addon uses a linked collection (CameraShakify.v2) by default or inadvertently.
A potential fix could involve ensuring the addon creates or uses a local collection for storing objects related to the new camera shakes. This could include verifying that the target collection is not linked before attempting to link objects.

**Comment by cessen** [comment]
Thank you for the report!

This is happening specifically because you have a camera in the library-linked data that already has Camera Shakify applied.  It doesn't happen with library linking in general.

Indeed, the fix will involve using a more sophisticated naming scheme for the camera shakify collection, as well as for the camera shakify helper objects in that collection.

In the mean time, this should be easy to work around by simply not linking other camera shakify cameras.  It's also possible that you've accidentally *directly* linked in the camera shakify collection from another file, in which case you should also not do that.

**Comment by 0xCarnival** [comment]
Thank you @cessen 

It happened that I linked a scene from **Project B** to **Project A** that also uses Camera Shakify. When I tried to Shakify a new camera on **Project A** it gave that error.

It all went to normal as soon as I _unlinked_ those scenes from **Project B**.

It could be that it also, as you said, it accidentaly linked the Camera Shakify Collection from **Project B**.

Anyway, thanks for your attention.
