### ISSUE TITLE
Shakify not working 

### ISSUE THREAD

**Issue by bahawerr** [EatTheFuture/camera_shakify#7]
Shakify worked fine before this error. Does anyone know why I am having this issue? 

Blender 3.1.2
Win 10
-----
"Python: Traceback (most recent call last):
  File "C:\Users\bahawerr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\camera_shakify-master\__init__.py", line 485, in execute
    rebuild_camera_shakes(camera, context)
  File "C:\Users\bahawerr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\camera_shakify-master\__init__.py", line 376, in rebuild_camera_shakes
    build_single_shake(camera, shake_item_index, collection, context)
  File "C:\Users\bahawerr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\camera_shakify-master\__init__.py", line 209, in build_single_shake
    constraint.frame_start = action_range[0]
TypeError: bpy_struct: item.attr = val: ActionConstraint.frame_start expected an int type, not float

location: <unknown location>:-1"

**Comment by bahawerr** [comment]
Solved.

**Comment by cessen** [comment]
It looks like the same issue as #6.  So I assume all you needed to do was upgrade to the latest version of Camera Shakify?

**Comment by Fender-Blender** [comment]
I'm trying to render a found footage scene that I used shakify for on sheepit. The manual camera movement is showing but not the shakify addon. I tried baking, I chose the blender 2.93 option, nothing works. Help.

**Comment by KunjBhesaniya** [comment]
> I'm trying to render a found footage scene that I used shakify for on sheepit. The manual camera movement is showing but not the shakify addon. I tried baking, I chose the blender 2.93 option, nothing works. Help.

I've got the same Issue
